language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.1


before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - composer require --no-update symfony/framework-bundle "$SYMFONY_VERSION"

install:
  - composer install --prefer-source

script: vendor/bin/phpunit --configuration Tests/phpunit.xml

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

matrix:
  include:
    - php: 5.3
      dist: precise

    - php: 5.5
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=3.0.*

    - php: 7.0
      env: SYMFONY_VERSION=3.1.*
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*

    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*

    - php: 7.1
      env: SYMFONY_VERSION=3.3.*

    - php: 7.1
      env:
        - DEPENDENCIES=beta
        - SYMFONY_VERSION=4.0.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

